export const SHOW_ALL = 'SHOW_ALL';

export const RECEIVE_CONTRACTORS = 'RECEIVE_CONTRACTORS';
export const CREATE_CONTRACTOR = 'CREATE_CONTRACTOR';

export const GET_ALL_CONTRACTORS = 'GET_ALL_CONTRACTORS';

export const ADD_CONTRACTOR_TO_FAVORITE = 'ADD_CONTRACTOR_TO_FAVORITE';
